use_frameworks!

target 'iOSBoilerplate_Example' do
  pod 'iOSBoilerplate', :path => '../'

  target 'iOSBoilerplate_Tests' do
    inherit! :search_paths

    use_frameworks!
    pod 'Nimble', '~> 6.0.0'    
  end
end
